#!/usr/bin/env bash
# System information / status report (Ubuntu-friendly, portable)

# ---------- Identity & time ----------
HOSTNAME=$(hostname)
USER_NAME=$(whoami)
NOW=$(date '+%Y-%m-%d %H:%M:%S %Z')

# ---------- OS / uptime ----------
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  OS="$PRETTY_NAME"
else
  OS="$(uname -sr)"
fi
UPTIME=$(uptime -p 2>/dev/null | sed 's/^up //')

# ---------- CPU / RAM ----------
CPU=$(lscpu 2>/dev/null | awk -F: '/Model name/ {gsub(/^[ \t]+/,"",$2); print $2; exit}')
[ -z "$CPU" ] && CPU=$(lshw -C processor 2>/dev/null | awk -F: '/product:/ {gsub(/^[ \t]+/,"",$2); print $2; exit}')
RAM=$(free -h 2>/dev/null | awk '/^Mem:/ {print $2 " total"}')

# ---------- Disks (all installed) ----------
DISKS=$(lsblk -dno NAME,MODEL,SIZE,TYPE 2>/dev/null | awk '$4=="disk"{printf "/dev/%s %s %s; ",$1,$2,$3}' | sed 's/; $//')

# ---------- Video ----------
VIDEO=$(lshw -C display 2>/dev/null | awk -F: '/product:/ {p=$2} /vendor:/ {v=$2} END{gsub(/^[ \t]+/,"",p); gsub(/^[ \t]+/,"",v); if(p||v) print v " " p}')
[ -z "$VIDEO" ] && VIDEO=$(lspci 2>/dev/null | awk -F': ' '/VGA/ {print $3; exit}')

# ---------- Networking (default route) ----------
GW_IF=$(ip route 2>/dev/null | awk '/^default/ {print $5; exit}')
HOST_IP=$([ -n "$GW_IF" ] && ip -4 -o addr show dev "$GW_IF" 2>/dev/null | awk '{print $4}' | cut -d/ -f1)
GATEWAY=$(ip route 2>/dev/null | awk '/^default/ {print $3; exit}')
DNS=$(resolvectl dns 2>/dev/null | awk '{for(i=3;i<=NF;i++)printf "%s ",$i}' | sed 's/ $//')
[ -z "$DNS" ] && DNS=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf 2>/dev/null | paste -sd' ' -)

# ---------- Status ----------
USERS=$(who 2>/dev/null | awk '{print $1}' | sort -u | paste -sd, -)
[ -z "$USERS" ] && USERS="(none)"
DISKSPACE=$(df -h -x tmpfs -x devtmpfs -x squashfs --output=target,avail 2>/dev/null | awk 'NR>1 {print $1" "$2}' | paste -sd', ' -)
PROCCOUNT=$(ps -e 2>/dev/null | wc -l)
LOADAVG=$(awk '{print $1", "$2", "$3}' /proc/loadavg 2>/dev/null)
PORTS=$(ss -tuln 2>/dev/null | awk 'NR>1 && ($1 ~ /tcp/ || $1 ~ /udp/){gsub(/.*:/,"",$5); if($5!="") print $5}' | sort -n | uniq | paste -sd', ' -)
[ -z "$PORTS" ] && PORTS="(none)"
UFW=$(sudo -n ufw status 2>/dev/null | head -n1)
[ -z "$UFW" ] && UFW=$(ufw status 2>/dev/null | head -n1)
[ -z "$UFW" ] && UFW="inactive/unknown"

# ---------- Output ----------
echo
cat <<REPORT
System Report for $HOSTNAME generated by $USER_NAME, on $NOW

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: ${HOST_IP:-unknown}
Gateway IP: ${GATEWAY:-unknown}
DNS Server: ${DNS:-unknown}

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISKSPACE
Process Count: $PROCCOUNT
Load Averages: $LOADAVG
Listening Network Ports: $PORTS
UFW Status: $UFW
REPORT
echo

